
package kw.com.gulfbank.wise.wiseintegrationservicesmanagement.service.wiseintegrationservices.intf._1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 *
 */
@WebService(name = "WiseIntegrationServices", targetNamespace = "http://wise.gulfbank.com.kw/wiseintegrationservicesmanagement/service/wiseintegrationservices/intf/1")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WiseIntegrationServices {


    /**
     *
     * 	 GetWiseInvestmentDetails- Operation name, input wrapper, output wrapper and fault wrapper.
     *
     *
     * @param getWiseInvestmentDetailsRequest
     * @return
     *     returns kw.com.gulfbank.wise.wiseintegrationservicesmanagement.service.wiseintegrationservices.intf._1.GetWiseInvestmentDetailsReply
     * @throws Fault_Exception
     */
    @WebMethod(operationName = "GetWiseInvestmentDetails", action = "GetWiseInvestmentDetails")
    @WebResult(name = "GetWiseInvestmentDetailsReply", targetNamespace = "")
    @RequestWrapper(localName = "GetWiseInvestmentDetails", targetNamespace = "http://wise.gulfbank.com.kw/wiseintegrationservicesmanagement/service/wiseintegrationservices/intf/1", className = "kw.com.gulfbank.wise.wiseintegrationservicesmanagement.service.wiseintegrationservices.intf._1.GetWiseInvestmentDetails")
    @ResponseWrapper(localName = "GetWiseInvestmentDetailsResponse", targetNamespace = "http://wise.gulfbank.com.kw/wiseintegrationservicesmanagement/service/wiseintegrationservices/intf/1", className = "kw.com.gulfbank.wise.wiseintegrationservicesmanagement.service.wiseintegrationservices.intf._1.GetWiseInvestmentDetailsResponse")
    @Action(input = "GetWiseInvestmentDetails", output = "GetWiseInvestmentDetailsResponse", fault = {
        @FaultAction(className = Fault_Exception.class, value = "http://wise.gulfbank.com.kw/wiseintegrationservicesmanagement/service/wiseintegrationservices/intf/1/WiseIntegrationServices/GetWiseInvestmentDetails/Fault/Fault")
    })
    public GetWiseInvestmentDetailsReply getWiseInvestmentDetails(
            @WebParam(name = "GetWiseInvestmentDetailsRequest", targetNamespace = "")
                    GetWiseInvestmentDetailsRequest getWiseInvestmentDetailsRequest)
        throws Fault_Exception
    ;

    /**
     *
     * 	 GetWiseInvestmentDetails- Operation name, input wrapper, output wrapper and fault wrapper.
     *
     *
     * @param getWiseDocumentsDetailsRequest
     * @return
     *     returns kw.com.gulfbank.wise.wiseintegrationservicesmanagement.service.wiseintegrationservices.intf._1.GetWiseDocumentsDetailsReply
     * @throws Fault_Exception
     */
    @WebMethod(operationName = "GetWiseDocumentsDetails", action = "GetWiseDocumentsDetails")
    @WebResult(name = "GetWiseDocumentsDetailsReply", targetNamespace = "")
    @RequestWrapper(localName = "GetWiseDocumentsDetails", targetNamespace = "http://wise.gulfbank.com.kw/wiseintegrationservicesmanagement/service/wiseintegrationservices/intf/1", className = "kw.com.gulfbank.wise.wiseintegrationservicesmanagement.service.wiseintegrationservices.intf._1.GetWiseDocumentsDetails")
    @ResponseWrapper(localName = "GetWiseDocumentsDetailsResponse", targetNamespace = "http://wise.gulfbank.com.kw/wiseintegrationservicesmanagement/service/wiseintegrationservices/intf/1", className = "kw.com.gulfbank.wise.wiseintegrationservicesmanagement.service.wiseintegrationservices.intf._1.GetWiseDocumentsDetailsResponse")
    @Action(input = "GetWiseDocumentsDetails", output = "GetWiseDocumentsDetailsResponse", fault = {
        @FaultAction(className = Fault_Exception.class, value = "http://wise.gulfbank.com.kw/wiseintegrationservicesmanagement/service/wiseintegrationservices/intf/1/WiseIntegrationServices/GetWiseInvestmentDetails/Fault/Fault")
    })
    public GetWiseDocumentsDetailsReply getWiseDocumentsDetails(
            @WebParam(name = "GetWiseDocumentsDetailsRequest", targetNamespace = "")
                    GetWiseDocumentsDetailsRequest getWiseDocumentsDetailsRequest)
        throws Fault_Exception
    ;

    /**
     *
     * 	 DownloadDocument- Operation name, input wrapper, output wrapper and fault wrapper.
     *
     *
     * @param downloadWiseDocumentRequest
     * @return
     *     returns kw.com.gulfbank.wise.wiseintegrationservicesmanagement.service.wiseintegrationservices.intf._1.DownloadWiseDocumentReply
     * @throws Fault_Exception
     */
    @WebMethod(operationName = "DownloadWiseDocument", action = "DownloadWiseDocument")
    @WebResult(name = "DownloadWiseDocumentReply", targetNamespace = "")
    @RequestWrapper(localName = "DownloadWiseDocument", targetNamespace = "http://wise.gulfbank.com.kw/wiseintegrationservicesmanagement/service/wiseintegrationservices/intf/1", className = "kw.com.gulfbank.wise.wiseintegrationservicesmanagement.service.wiseintegrationservices.intf._1.DownloadWiseDocument")
    @ResponseWrapper(localName = "DownloadWiseDocumentResponse", targetNamespace = "http://wise.gulfbank.com.kw/wiseintegrationservicesmanagement/service/wiseintegrationservices/intf/1", className = "kw.com.gulfbank.wise.wiseintegrationservicesmanagement.service.wiseintegrationservices.intf._1.DownloadWiseDocumentResponse")
    @Action(input = "DownloadWiseDocument", output = "DownloadWiseDocumentResponse", fault = {
        @FaultAction(className = Fault_Exception.class, value = "http://wise.gulfbank.com.kw/wiseintegrationservicesmanagement/service/wiseintegrationservices/intf/1/WiseIntegrationServices/DownloadDocument/Fault/Fault")
    })
    public DownloadWiseDocumentReply downloadWiseDocument(
            @WebParam(name = "DownloadWiseDocumentRequest", targetNamespace = "")
                    DownloadWiseDocumentRequest downloadWiseDocumentRequest)
        throws Fault_Exception
    ;

    /**
     *
     * 	 DownloadDocument- Operation name, input wrapper, output wrapper and fault wrapper.
     *
     *
     * @param generateSessionRequest
     * @return
     *     returns kw.com.gulfbank.wise.wiseintegrationservicesmanagement.service.wiseintegrationservices.intf._1.GenerateSessionReply
     * @throws Fault_Exception
     */
    @WebMethod(operationName = "GenerateSession", action = "GenerateSession")
    @WebResult(name = "GenerateSessionReply", targetNamespace = "")
    @RequestWrapper(localName = "GenerateSession", targetNamespace = "http://wise.gulfbank.com.kw/wiseintegrationservicesmanagement/service/wiseintegrationservices/intf/1", className = "kw.com.gulfbank.wise.wiseintegrationservicesmanagement.service.wiseintegrationservices.intf._1.GenerateSession")
    @ResponseWrapper(localName = "GenerateSessionResponse", targetNamespace = "http://wise.gulfbank.com.kw/wiseintegrationservicesmanagement/service/wiseintegrationservices/intf/1", className = "kw.com.gulfbank.wise.wiseintegrationservicesmanagement.service.wiseintegrationservices.intf._1.GenerateSessionResponse")
    @Action(input = "GenerateSession", output = "GenerateSessionResponse", fault = {
        @FaultAction(className = Fault_Exception.class, value = "http://wise.gulfbank.com.kw/wiseintegrationservicesmanagement/service/wiseintegrationservices/intf/1/WiseIntegrationServices/DownloadDocument/Fault/Fault")
    })
    public GenerateSessionReply generateSession(
            @WebParam(name = "GenerateSessionRequest", targetNamespace = "")
                    GenerateSessionRequest generateSessionRequest)
        throws Fault_Exception
    ;

}
